### ISSUE TITLE
Cannot find controlDict

### ISSUE THREAD

**Issue by KerrickC** [KerrickC/dcoker-openfoam-sh#3]
--> FOAM FATAL ERROR: 
cannot find file "/home/openfoam/system/controlDict"

//possible sources
not important env vars properly
permissions
file doesnt exist

**Comment by FerielYousfi** [comment]
Hello , I have a similar problem right now so please if you still remember the solution ,please help me and thank you .

**Comment by KerrickC** [comment]
Hi @FerielYousfi ,
Please make sure that you are properly important all necessary environment variables into your docker container. This was the source of the issue was having. You must tell the container where to find the directory using env vars.

**Comment by FerielYousfi** [comment]
I am working on the native windows openfoam version , i didn't need to
install Docker
thank you for your time

**Comment by Nawaraj23** [comment]
@FerielYousfi How did you solve your problem? I am also having same issues with OpenFoam v2212.
